#!/usr/bin/env bash
# =============================================================================
# SysScope (bundled single-file build) — auto-generated by build.sh
# Do NOT edit this file directly; edit the modular sysscope/*.sh sources,
# then re-run ./build.sh. License: MIT.
# =============================================================================

# ----------------------------- lib_core.sh -----------------------------
# =============================================================================
# SysScope — lib_core.sh
# Core library: output formatting, OS/arch detection, prompts, small helpers.
# bash 3.2+ compatible (no associative arrays, no ${var,,}).
# This file only DEFINES functions/vars; it runs nothing on its own.
# =============================================================================

# ---- Global config defaults (audit.sh may override before calling) ---------
: "${USE_COLOR:=1}"        # 1=color when on a TTY, 0=never
: "${INTERACTIVE:=0}"      # 1=ask questions, 0=use defaults
: "${REDACT:=0}"           # 1=hide serials/UUIDs/hostnames for sharing
: "${REPORT_FILE:=}"       # markdown report path ("" = none)
: "${JSON_FILE:=}"         # json output path ("" = none)
: "${EMIT_JSON:=0}"        # 1=write JSON
: "${DEEP:=0}"             # 1=run slower deep probes (e.g. du of home)
: "${_JSON_FIRST:=1}"      # internal: comma tracking for JSON

# ---- Colors -----------------------------------------------------------------
setup_colors() {
  if [ "$USE_COLOR" = "1" ] && [ -t 1 ]; then
    RST=$'\033[0m';  BOLD=$'\033[1m'; DIM=$'\033[2m'
    RED=$'\033[31m'; GRN=$'\033[32m'; YLW=$'\033[33m'
    BLU=$'\033[34m'; MAG=$'\033[35m'; CYN=$'\033[36m'
  else
    RST=''; BOLD=''; DIM=''; RED=''; GRN=''; YLW=''; BLU=''; MAG=''; CYN=''
  fi
}

# ---- Small helpers ----------------------------------------------------------
have()  { command -v "$1" >/dev/null 2>&1; }
lc()    { printf '%s' "$1" | tr '[:upper:]' '[:lower:]'; }
trim()  { printf '%s' "$1" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'; }

os_type() {
  case "$(uname -s 2>/dev/null)" in
    Darwin) printf 'macos' ;;
    Linux)  printf 'linux' ;;
    *)      printf 'other' ;;
  esac
}

# Redact a value when REDACT=1 (used for serials, UUIDs, hostnames, user paths)
rd() {
  if [ "$REDACT" = "1" ] && [ -n "$1" ]; then printf '‹redacted›'; else printf '%s' "$1"; fi
}

# bytes -> "12.3 GB"
bytes_to_gb() { awk -v b="${1:-0}" 'BEGIN{printf "%.1f", b/1073741824}'; }
# 1K-blocks -> integer GB
kb_to_gb()    { awk -v k="${1:-0}" 'BEGIN{printf "%.0f", k/1048576}'; }

# ---- Report sink (append a raw line to the markdown report) -----------------
r() { [ -n "$REPORT_FILE" ] && printf '%s\n' "$1" >> "$REPORT_FILE"; return 0; }

# ---- JSON sink (scalar key/values only) -------------------------------------
j() {
  [ "$EMIT_JSON" = "1" ] || return 0
  [ -n "$JSON_FILE" ] || return 0
  local k v
  k="$1"; v="$2"
  v=$(printf '%s' "$v" | sed 's/\\/\\\\/g; s/"/\\"/g')
  if [ "$_JSON_FIRST" = "1" ]; then _JSON_FIRST=0; else printf ',\n' >> "$JSON_FILE"; fi
  printf '  "%s": "%s"' "$k" "$v" >> "$JSON_FILE"
}

# ---- Pretty output (terminal) + mirrored markdown (report) ------------------
section() {                      # H2 / major section
  printf '\n%s%s== %s ==%s\n' "$BOLD" "$CYN" "$1" "$RST"
  r ""; r "## $1"; r ""
}
subsection() {                   # H3 / minor heading
  printf '\n%s  %s%s\n' "$BOLD" "$1" "$RST"
  r ""; r "### $1"; r ""
}
field() {                        # key/value: terminal + "- **key:** value"
  printf '  %s%-22s%s %s\n' "$BOLD" "$1" "$RST" "$2"
  r "- **$1:** $2"
}
bullet() {                       # list item
  printf '    %s-%s %s\n' "$DIM" "$RST" "$1"
  r "- $1"
}
note() {                         # dim aside / blockquote
  printf '  %s%s%s\n' "$DIM" "$1" "$RST"
  r ""; r "> $1"; r ""
}
status() {                       # level in {ok,warn,err,info}
  local lvl icon col rep
  lvl="$1"
  case "$lvl" in
    ok)   icon='OK '; col="$GRN"; rep='✅' ;;
    warn) icon='!! '; col="$YLW"; rep='⚠️' ;;
    err)  icon='XX '; col="$RED"; rep='🟥' ;;
    info) icon='.. '; col="$BLU"; rep='ℹ️' ;;
    *)    icon='-- '; col="$RST"; rep='' ;;
  esac
  printf '  %s[%s]%s %s\n' "$col" "$icon" "$RST" "$2"
  r "- $rep $2"
}
hr() { printf '%s%s%s\n' "$DIM" "------------------------------------------------------------" "$RST"; }

# ---- Interactive prompts (read from /dev/tty so redirected stdout is OK) ----
ask_yn() {                       # ask_yn "Question?" [y|n]  -> exit 0 = yes
  local q def hint ans
  q="$1"; def="${2:-y}"
  if [ "$INTERACTIVE" != "1" ]; then [ "$def" = "y" ]; return; fi
  hint='[Y/n]'; [ "$def" = "n" ] && hint='[y/N]'
  printf '%s? %s %s%s ' "$CYN" "$q" "$hint" "$RST" > /dev/tty
  read -r ans < /dev/tty || ans=''
  ans=$(lc "$ans"); [ -z "$ans" ] && ans="$def"
  [ "$ans" = "y" ] || [ "$ans" = "yes" ]
}
ask_str() {                      # ask_str "Prompt" "default" -> echoes value
  local q def ans
  q="$1"; def="$2"
  if [ "$INTERACTIVE" != "1" ]; then printf '%s' "$def"; return; fi
  printf '%s> %s%s [%s]: ' "$CYN" "$q" "$RST" "$def" > /dev/tty
  read -r ans < /dev/tty || ans=''
  [ -z "$ans" ] && ans="$def"
  printf '%s' "$ans"
}
ask_menu() {                     # ask_menu "Title" "opt1" "opt2" ... -> echoes chosen index (1-based)
  local title n i choice
  title="$1"; shift
  if [ "$INTERACTIVE" != "1" ]; then printf '1'; return; fi
  printf '\n%s%s%s\n' "$BOLD" "$title" "$RST" > /dev/tty
  i=1
  for o in "$@"; do printf '   %s%d)%s %s\n' "$CYN" "$i" "$RST" "$o" > /dev/tty; i=$((i+1)); done
  n=$#
  printf '%sChoose [1-%d] (default 1): %s' "$CYN" "$n" "$RST" > /dev/tty
  read -r choice < /dev/tty || choice=''
  case "$choice" in (''|*[!0-9]*) choice=1 ;; esac
  [ "$choice" -ge 1 ] 2>/dev/null && [ "$choice" -le "$n" ] 2>/dev/null || choice=1
  printf '%s' "$choice"
}

# ----------------------------- lib_report.sh -----------------------------
# =============================================================================
# SysScope — lib_report.sh
# Markdown report + JSON document lifecycle (header/footer, tables).
# Depends on lib_core.sh (r, j, REDACT, REPORT_FILE, JSON_FILE, EMIT_JSON).
# =============================================================================

SYSSCOPE_GIST_URL="${SYSSCOPE_GIST_URL:-https://github.com/aoneahsan/sysscope}"

report_init() {
  [ -n "$REPORT_FILE" ] || return 0
  : > "$REPORT_FILE" 2>/dev/null || { printf 'Cannot write report to %s\n' "$REPORT_FILE" >&2; REPORT_FILE=''; return 1; }
  r "# 🔭 SysScope — System Audit & AI-Readiness Report"
  r ""
  r "_Generated: $(date '+%Y-%m-%d %H:%M:%S %Z')_"
  r ""
  if [ "$REDACT" = "1" ]; then
    r "> 🔒 **Privacy mode on** — serial numbers, UUIDs and hostnames have been redacted so this report is safe to share publicly."
    r ""
  fi
  r "This report was produced by **SysScope**, a portable system-capability auditor."
  r "It summarizes your hardware, installed developer/AI software, and what kinds of"
  r "local AI models and CPU/GPU workloads this machine can realistically run."
  r ""
  r "---"
}

report_finalize() {
  [ -n "$REPORT_FILE" ] || return 0
  r ""
  r "---"
  r ""
  r "### 💬 Feedback & contributions"
  r ""
  r "SysScope is open and meant to improve from real-world machines."
  r "If a value looked wrong on your system, or you want a check added:"
  r ""
  r "- Leave a comment on the gist: $SYSSCOPE_GIST_URL"
  r "- Include your OS, chip, and the line that looked off (no need to share serials)."
  r ""
  r "_Re-run any time with \`./audit.sh\`. Generate a shareable copy with \`./audit.sh --share\`._"
}

# Begin/end a GitHub-Flavored-Markdown table. Header cells passed as args.
table_begin() {
  local header sep c
  header='|'; sep='|'
  for c in "$@"; do header="$header $c |"; sep="$sep --- |"; done
  r "$header"; r "$sep"
}
table_row() {                    # each arg = one cell
  local row c
  row='|'
  for c in "$@"; do row="$row $c |"; done
  r "$row"
}

# JSON lifecycle
json_init() {
  [ "$EMIT_JSON" = "1" ] || return 0
  [ -n "$JSON_FILE" ] || return 0
  : > "$JSON_FILE" 2>/dev/null || { EMIT_JSON=0; return 1; }
  printf '{\n' >> "$JSON_FILE"
  _JSON_FIRST=1
}
json_finalize() {
  [ "$EMIT_JSON" = "1" ] || return 0
  [ -n "$JSON_FILE" ] || return 0
  printf '\n}\n' >> "$JSON_FILE"
}

# ----------------------------- mod_system.sh -----------------------------
# =============================================================================
# SysScope — mod_system.sh : system identity (OS, model, chip, kernel)
# Sets globals: SYS_OS SYS_ARCH SYS_OSNAME SYS_OSVER SYS_MODELNAME SYS_MODELID
#               SYS_CHIP SYS_SERIAL SYS_HOST
# =============================================================================

mod_system() {
  section "System Identity"
  SYS_OS=$(os_type)
  SYS_ARCH=$(uname -m 2>/dev/null)
  local build kernel
  kernel=$(uname -sr 2>/dev/null)
  SYS_HOST=$(hostname 2>/dev/null)

  if [ "$SYS_OS" = "macos" ]; then
    SYS_OSNAME="macOS"
    SYS_OSVER=$(sw_vers -productVersion 2>/dev/null)
    build=$(sw_vers -buildVersion 2>/dev/null)
    SYS_MODELID=$(sysctl -n hw.model 2>/dev/null)
    SYS_MODELNAME=$(system_profiler SPHardwareDataType 2>/dev/null | awk -F': ' '/Model Name/{print $2; exit}')
    SYS_CHIP=$(system_profiler SPHardwareDataType 2>/dev/null | awk -F': ' '/Chip/{print $2; exit}')
    [ -z "$SYS_CHIP" ] && SYS_CHIP=$(sysctl -n machdep.cpu.brand_string 2>/dev/null)
    SYS_SERIAL=$(system_profiler SPHardwareDataType 2>/dev/null | awk -F': ' '/Serial Number/{print $2; exit}')
  elif [ "$SYS_OS" = "linux" ]; then
    SYS_OSNAME=$( ( . /etc/os-release 2>/dev/null; printf '%s' "$PRETTY_NAME" ) )
    [ -z "$SYS_OSNAME" ] && SYS_OSNAME="Linux"
    SYS_OSVER=$(uname -r 2>/dev/null)
    SYS_MODELNAME=$(cat /sys/devices/virtual/dmi/id/product_name 2>/dev/null)
    SYS_MODELID=$(cat /sys/devices/virtual/dmi/id/product_version 2>/dev/null)
    SYS_CHIP=$(awk -F': ' '/model name/{print $2; exit}' /proc/cpuinfo 2>/dev/null)
    SYS_SERIAL=""
  else
    SYS_OSNAME=$(uname -s 2>/dev/null); SYS_OSVER=$(uname -r 2>/dev/null)
    SYS_MODELNAME=""; SYS_MODELID=""; SYS_CHIP=""; SYS_SERIAL=""
  fi

  field "Operating system" "$SYS_OSNAME $SYS_OSVER"
  [ -n "$build" ] && field "Build" "$build"
  field "Kernel" "$kernel"
  field "Architecture" "$SYS_ARCH"
  if [ -n "$SYS_MODELNAME" ]; then
    if [ -n "$SYS_MODELID" ]; then field "Model" "$SYS_MODELNAME ($SYS_MODELID)"; else field "Model" "$SYS_MODELNAME"; fi
  fi
  [ -n "$SYS_CHIP" ] && field "Chip / CPU" "$SYS_CHIP"
  field "Hostname" "$(rd "$SYS_HOST")"
  [ -n "$SYS_SERIAL" ] && field "Serial number" "$(rd "$SYS_SERIAL")"

  case "$SYS_ARCH" in
    arm64|aarch64) status info "ARM (Apple Silicon / aarch64) — note: virtualization runs ARM guest OSes only." ;;
  esac

  j os "$SYS_OSNAME $SYS_OSVER"
  j arch "$SYS_ARCH"
  j model "$SYS_MODELNAME"
  j chip "$SYS_CHIP"
}

# ----------------------------- mod_cpu.sh -----------------------------
# =============================================================================
# SysScope — mod_cpu.sh : processor topology
# Sets globals: CPU_BRAND CPU_PHYS CPU_LOGICAL CPU_P CPU_E
# =============================================================================

mod_cpu() {
  section "CPU"
  CPU_BRAND=""; CPU_PHYS=""; CPU_LOGICAL=""; CPU_P=""; CPU_E=""

  if [ "$SYS_OS" = "macos" ]; then
    CPU_BRAND=$(sysctl -n machdep.cpu.brand_string 2>/dev/null)
    CPU_PHYS=$(sysctl -n hw.physicalcpu 2>/dev/null)
    CPU_LOGICAL=$(sysctl -n hw.logicalcpu 2>/dev/null)
    CPU_P=$(sysctl -n hw.perflevel0.physicalcpu 2>/dev/null)
    CPU_E=$(sysctl -n hw.perflevel1.physicalcpu 2>/dev/null)
  elif [ "$SYS_OS" = "linux" ]; then
    CPU_BRAND=$(awk -F': ' '/model name/{print $2; exit}' /proc/cpuinfo 2>/dev/null)
    CPU_LOGICAL=$(nproc 2>/dev/null)
    CPU_PHYS=$(awk -F': ' '/^cpu cores/{print $2; exit}' /proc/cpuinfo 2>/dev/null)
  fi

  [ -n "$CPU_BRAND" ]   && field "Processor" "$CPU_BRAND"
  [ -n "$CPU_PHYS" ]    && field "Physical cores" "$CPU_PHYS"
  [ -n "$CPU_LOGICAL" ] && field "Logical cores" "$CPU_LOGICAL"
  if [ -n "$CPU_P" ] && [ -n "$CPU_E" ] && [ "${CPU_P:-0}" -gt 0 ] 2>/dev/null; then
    field "Core layout" "$CPU_P performance + $CPU_E efficiency"
    bullet "Performance cores handle foreground builds/inference; efficiency cores absorb background work."
  fi

  j cpu_brand "$CPU_BRAND"
  j cpu_logical "${CPU_LOGICAL:-}"
  j cpu_physical "${CPU_PHYS:-}"
}

# ----------------------------- mod_memory.sh -----------------------------
# =============================================================================
# SysScope — mod_memory.sh : RAM, swap, memory pressure
# Sets globals: MEM_TOTAL_GB (int) MEM_BYTES MEM_FREE_PCT SWAP_USED
# =============================================================================

mod_memory() {
  section "Memory (RAM)"
  MEM_BYTES=0; MEM_FREE_PCT=""; SWAP_USED=""

  if [ "$SYS_OS" = "macos" ]; then
    MEM_BYTES=$(sysctl -n hw.memsize 2>/dev/null)
    SWAP_USED=$(sysctl -n vm.swapusage 2>/dev/null | sed -n 's/.*used = \([0-9.]*[A-Za-z]*\).*/\1/p')
    MEM_FREE_PCT=$(memory_pressure 2>/dev/null | awk -F': ' '/free percentage/{gsub(/%/,"",$2); print $2; exit}')
  elif [ "$SYS_OS" = "linux" ]; then
    MEM_BYTES=$(awk '/MemTotal/{print $2*1024; exit}' /proc/meminfo 2>/dev/null)
    local avail tot
    avail=$(awk '/MemAvailable/{print $2; exit}' /proc/meminfo 2>/dev/null)
    tot=$(awk '/MemTotal/{print $2; exit}' /proc/meminfo 2>/dev/null)
    [ -n "$avail" ] && [ -n "$tot" ] && MEM_FREE_PCT=$(awk -v a="$avail" -v t="$tot" 'BEGIN{printf "%.0f", a/t*100}')
    SWAP_USED=$(awk '/SwapTotal/{t=$2} /SwapFree/{f=$2} END{printf "%.0f MB", (t-f)/1024}' /proc/meminfo 2>/dev/null)
  fi

  MEM_TOTAL_GB=$(awk -v b="${MEM_BYTES:-0}" 'BEGIN{printf "%.0f", b/1073741824}')
  field "Total RAM" "${MEM_TOTAL_GB} GB"
  [ -n "$MEM_FREE_PCT" ] && field "Free (approx)" "${MEM_FREE_PCT}%"
  [ -n "$SWAP_USED" ]    && field "Swap in use" "$SWAP_USED"

  # RAM class verdict
  if   [ "${MEM_TOTAL_GB:-0}" -ge 32 ] 2>/dev/null; then status ok   "Plenty of RAM — comfortable for parallel heavy workloads and larger local models."
  elif [ "${MEM_TOTAL_GB:-0}" -ge 16 ] 2>/dev/null; then status ok   "Solid RAM — great for dev; run ONE very-heavy workload (big model / VM / emulator) at a time."
  elif [ "${MEM_TOTAL_GB:-0}" -ge 8  ] 2>/dev/null; then status warn "Limited RAM — fine for light dev and 3–8B models; avoid stacking heavy apps."
  else status err "Low RAM — only small models (1–3B) and light tasks will run smoothly."
  fi

  # swap pressure hint (macOS value has a unit suffix)
  case "$SWAP_USED" in
    0.00M|0M|0\ MB|"") : ;;
    *) note "Some swap is in use — the system is spilling RAM to disk. Close apps before launching a model/VM." ;;
  esac

  j ram_gb "$MEM_TOTAL_GB"
}

# ----------------------------- mod_gpu.sh -----------------------------
# =============================================================================
# SysScope — mod_gpu.sh : GPU, unified vs discrete memory, accelerators
# Sets globals: GPU_NAME GPU_CORES GPU_VRAM_GB IS_UNIFIED
# =============================================================================

mod_gpu() {
  section "Graphics (GPU) & Accelerators"
  GPU_NAME=""; GPU_CORES=""; GPU_VRAM_GB="0"; IS_UNIFIED=0

  if [ "$SYS_OS" = "macos" ]; then
    GPU_NAME=$(system_profiler SPDisplaysDataType 2>/dev/null | awk -F': ' '/Chipset Model/{print $2; exit}')
    GPU_CORES=$(system_profiler SPDisplaysDataType 2>/dev/null | awk -F': ' '/Total Number of Cores/{print $2; exit}')
    local metal
    metal=$(system_profiler SPDisplaysDataType 2>/dev/null | awk -F': ' '/Metal/{print $2; exit}')
    case "$SYS_ARCH" in arm64|aarch64) IS_UNIFIED=1 ;; esac

    [ -n "$GPU_NAME" ]  && field "GPU" "$GPU_NAME"
    [ -n "$GPU_CORES" ] && field "GPU cores" "$GPU_CORES"
    [ -n "$metal" ]     && field "Graphics API" "Metal ($metal)"

    if [ "$IS_UNIFIED" = "1" ]; then
      field "Memory model" "Unified — GPU shares the ${MEM_TOTAL_GB:-?} GB system RAM"
      status info "Apple Silicon: local LLMs run on the GPU via Metal. The Neural Engine (Core ML) is NOT used by Ollama/llama.cpp."
      bullet "There is no separate VRAM — the model lives in your single RAM pool, which is why total RAM is the AI ceiling."
    fi

  elif [ "$SYS_OS" = "linux" ]; then
    if have nvidia-smi; then
      GPU_NAME=$(nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null | head -1)
      local vram
      vram=$(nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits 2>/dev/null | head -1)
      [ -n "$vram" ] && GPU_VRAM_GB=$(awk -v m="$vram" 'BEGIN{printf "%.1f", m/1024}')
      [ -n "$GPU_NAME" ] && field "GPU" "$GPU_NAME (NVIDIA)"
      [ "$GPU_VRAM_GB" != "0" ] && field "VRAM" "${GPU_VRAM_GB} GB"
      status ok "Discrete NVIDIA GPU — VRAM is the limiter for fast local inference."
    elif have rocminfo || have rocm-smi; then
      GPU_NAME=$(lspci 2>/dev/null | grep -iE 'vga|3d|display' | sed 's/.*: //' | head -1)
      field "GPU" "${GPU_NAME:-AMD ROCm device}"
      status info "AMD GPU detected — ROCm-capable runtimes can use it (setup varies)."
    else
      GPU_NAME=$(lspci 2>/dev/null | grep -iE 'vga|3d|display' | sed 's/.*: //' | head -1)
      field "GPU" "${GPU_NAME:-unknown (install nvidia-smi/lspci for detail)}"
      status info "No discrete-GPU VRAM detected — local models would run on CPU (much slower)."
    fi
  fi

  j gpu "${GPU_NAME:-}"
  j gpu_cores "${GPU_CORES:-}"
  j gpu_vram_gb "${GPU_VRAM_GB:-0}"
  j unified_memory "$IS_UNIFIED"
}

# ----------------------------- mod_storage.sh -----------------------------
# =============================================================================
# SysScope — mod_storage.sh : disk capacity, free space, biggest items
# Sets globals: DISK_TOTAL_GB DISK_FREE_GB DISK_USED_PCT
# =============================================================================

mod_storage() {
  section "Storage"
  local target line tot used avail cap
  if [ "$SYS_OS" = "macos" ]; then
    target="/System/Volumes/Data"; [ -d "$target" ] || target="/"
  else
    target="/"
  fi

  # -P = POSIX one-line output (avoids wrapped device names); -k = 1024 blocks
  line=$(df -Pk "$target" 2>/dev/null | awk 'NR==2{print $2, $3, $4, $5}')
  tot=$(printf '%s'  "$line" | awk '{print $1}')
  used=$(printf '%s' "$line" | awk '{print $2}')
  avail=$(printf '%s' "$line" | awk '{print $3}')
  cap=$(printf '%s'  "$line" | awk '{print $4}')

  DISK_TOTAL_GB=$(kb_to_gb "${tot:-0}")
  DISK_FREE_GB=$(kb_to_gb "${avail:-0}")
  DISK_USED_PCT=$(printf '%s' "$cap" | tr -d '%')

  field "Volume" "$target"
  field "Total capacity" "${DISK_TOTAL_GB} GB"
  field "Free space" "${DISK_FREE_GB} GB"
  field "Used" "${cap}"

  if [ -n "$DISK_USED_PCT" ]; then
    if   [ "$DISK_USED_PCT" -ge 90 ] 2>/dev/null; then
      status err "Disk is ${DISK_USED_PCT}% full (only ${DISK_FREE_GB} GB free). Reclaim space BEFORE installing new tools/models."
    elif [ "$DISK_USED_PCT" -ge 75 ] 2>/dev/null; then
      status warn "Disk ${DISK_USED_PCT}% full (${DISK_FREE_GB} GB free) — getting tight; plan cleanup soon."
    else
      status ok "Healthy free space (${DISK_FREE_GB} GB free)."
    fi
  fi

  # Deep probe: biggest items in home (slow on large homes; opt-in)
  if [ "$DEEP" = "1" ]; then
    subsection "Largest items in your home folder"
    note "Scanning ~ — this can take a moment…"
    # Folder names in $HOME are personal data — they routinely carry employer,
    # client and project names. Under --share (REDACT=1) the report is presented
    # as safe to post publicly, so the NAME is withheld and only the size, which
    # is the diagnostic signal, is kept.
    [ "$REDACT" = "1" ] && note "Folder names are withheld in share mode; sizes only."
    ( cd "$HOME" 2>/dev/null && du -sh -- * .[!.]* 2>/dev/null | sort -rh | head -10 ) | \
      while IFS= read -r liney; do
        [ -n "$liney" ] || continue
        if [ "$REDACT" = "1" ]; then
          bullet "$(printf '%s' "$liney" | cut -f1)	$(rd "x")"
        else
          bullet "$liney"
        fi
      done
  fi

  j disk_total_gb "$DISK_TOTAL_GB"
  j disk_free_gb "$DISK_FREE_GB"
  j disk_used_pct "$DISK_USED_PCT"
}

# ----------------------------- mod_power.sh -----------------------------
# =============================================================================
# SysScope — mod_power.sh : battery health, charge, thermal throttling
# Sets globals: PWR_PCT PWR_SRC PWR_ONBATT
# =============================================================================

mod_power() {
  PWR_PCT=""; PWR_SRC=""; PWR_ONBATT=0

  if [ "$SYS_OS" = "macos" ]; then
    section "Power, Battery & Thermals"
    local batt
    batt=$(pmset -g batt 2>/dev/null)
    if printf '%s' "$batt" | grep -q "InternalBattery"; then
      PWR_PCT=$(printf '%s' "$batt" | sed -n 's/.*[^0-9]\([0-9][0-9]*\)%.*/\1/p' | head -1)
      PWR_SRC=$(printf '%s' "$batt" | awk -F"'" '/Now drawing/{print $2; exit}')
      printf '%s' "$PWR_SRC" | grep -qi "battery" && PWR_ONBATT=1
      local health cycles cond
      health=$(system_profiler SPPowerDataType 2>/dev/null | awk -F': ' '/Maximum Capacity/{print $2; exit}')
      cycles=$(system_profiler SPPowerDataType 2>/dev/null | awk -F': ' '/Cycle Count/{print $2; exit}')
      cond=$(system_profiler SPPowerDataType 2>/dev/null | awk -F': ' '/Condition/{print $2; exit}')
      field "Power source" "${PWR_SRC:-unknown}"
      field "Charge" "${PWR_PCT}%"
      [ -n "$health" ] && field "Battery max capacity" "$health"
      [ -n "$cycles" ] && field "Cycle count" "$cycles"
      [ -n "$cond" ]   && field "Battery condition" "$cond"
      if [ -n "$PWR_PCT" ] && [ "$PWR_ONBATT" = "1" ] && [ "$PWR_PCT" -le 20 ] 2>/dev/null; then
        status warn "Battery low (${PWR_PCT}%) and running on battery — plug in before heavy/sustained workloads."
      fi
    else
      field "Power" "AC / desktop (no internal battery)"
    fi

    # Thermal / CPU speed limit
    local lim
    lim=$(pmset -g therm 2>/dev/null | sed -n 's/.*CPU_Speed_Limit *= *\([0-9]*\).*/\1/p' | head -1)
    if [ -n "$lim" ] && [ "$lim" != "100" ] 2>/dev/null; then
      status warn "CPU speed currently limited to ${lim}% (thermal or power throttling active)."
    fi

    # Fanless note for MacBook Air
    if printf '%s' "$SYS_MODELNAME" | grep -qi "MacBook Air"; then
      status info "This is a fanless MacBook Air — sustained heavy loads (long builds, long inference, video encodes) will thermally throttle. Keep it on AC and well-ventilated."
    fi

  elif [ "$SYS_OS" = "linux" ]; then
    if [ -r /sys/class/power_supply/BAT0/capacity ]; then
      section "Power & Battery"
      PWR_PCT=$(cat /sys/class/power_supply/BAT0/capacity 2>/dev/null)
      local stat
      stat=$(cat /sys/class/power_supply/BAT0/status 2>/dev/null)
      field "Charge" "${PWR_PCT}%"
      [ -n "$stat" ] && field "Status" "$stat"
    fi
  fi

  j battery_pct "${PWR_PCT:-}"
}

# ----------------------------- mod_software.sh -----------------------------
# =============================================================================
# SysScope — mod_software.sh : developer & AI toolchain inventory
# =============================================================================

# sw_check <command> <label> <version-cmd-or-empty>
sw_check() {
  local cmd label vcmd ver
  cmd="$1"; label="$2"; vcmd="$3"
  if have "$cmd"; then
    if [ -n "$vcmd" ]; then
      ver=$($vcmd 2>&1 | head -1)
      ver=$(trim "$ver")
      status ok "$label — ${ver:-installed}"
    else
      status ok "$label — installed"
    fi
  else
    status info "$label — not installed"
  fi
}

# ls_app <AppName> (macOS .app presence)
ls_app() {
  [ "$SYS_OS" = "macos" ] || return 0
  local app="$1"
  if [ -d "/Applications/$app.app" ] || [ -d "$HOME/Applications/$app.app" ]; then
    status ok "$app — installed"
  else
    status info "$app — not installed"
  fi
}

# py_pkg <module> <label>  (report only if present)
py_pkg() {
  local mod label ver
  mod="$1"; label="$2"
  have python3 || return 0
  ver=$(python3 - "$mod" <<'PYEOF' 2>/dev/null
import importlib, sys
try:
    m = importlib.import_module(sys.argv[1])
    sys.stdout.write(getattr(m, "__version__", "installed"))
except Exception:
    pass
PYEOF
)
  [ -n "$ver" ] && status ok "$label (Python) — $ver"
}

mod_software() {
  section "Developer & AI Software"

  subsection "Languages & runtimes"
  sw_check node    "Node.js"  "node --version"
  sw_check python3 "Python"   "python3 --version"
  sw_check ruby    "Ruby"     "ruby --version"
  sw_check go      "Go"       "go version"
  sw_check rustc   "Rust"     "rustc --version"
  sw_check java    "Java"     "java -version"
  sw_check php     "PHP"      "php --version"

  subsection "Package managers"
  sw_check brew  "Homebrew" "brew --version"
  sw_check npm   "npm"      "npm --version"
  sw_check pnpm  "pnpm"     "pnpm --version"
  sw_check yarn  "yarn"     "yarn --version"
  sw_check pip3  "pip"      "pip3 --version"
  sw_check uv    "uv"       "uv --version"

  subsection "Containers & virtualization"
  sw_check docker  "Docker"   "docker --version"
  sw_check orb     "OrbStack" "orb version"
  sw_check vagrant "Vagrant"  "vagrant --version"
  ls_app "VMware Fusion"
  ls_app "Parallels Desktop"
  ls_app "UTM"

  subsection "AI / LLM tooling"
  sw_check ollama          "Ollama"     "ollama --version"
  sw_check llama-cli       "llama.cpp"  "llama-cli --version"
  sw_check mlx_lm.generate "MLX-LM"     ""
  py_pkg torch        "PyTorch"
  py_pkg tensorflow   "TensorFlow"
  py_pkg transformers "Transformers"
  py_pkg mlx          "MLX"
  if have ollama; then
    local models
    models=$(ollama list 2>/dev/null | awk 'NR>1{print $1}' | tr '\n' ' ')
    models=$(trim "$models")
    if [ -n "$models" ]; then
      subsection "Installed Ollama models"
      bullet "$models"
    fi
  fi

  subsection "Editors & build tools"
  sw_check git  "Git"            "git --version"
  sw_check code "VS Code (code)" ""
  if [ "$SYS_OS" = "macos" ]; then
    sw_check xcodebuild "Xcode" "xcodebuild -version"
    if have xcrun; then
      local rts
      rts=$(xcrun simctl list runtimes 2>/dev/null | grep -ci "iOS\|watchOS\|tvOS")
      if [ "${rts:-0}" -gt 0 ] 2>/dev/null; then
        status ok "iOS/Sim runtimes — ${rts} installed"
      else
        status info "iOS Simulator runtimes — none downloaded yet (each ~7–8 GB)"
      fi
    fi
  fi
}

# ----------------------------- mod_ai.sh -----------------------------
# =============================================================================
# SysScope — mod_ai.sh : Local AI / LLM capability assessment (the centerpiece)
# Uses MEM_TOTAL_GB, GPU_VRAM_GB, IS_UNIFIED, SYS_ARCH from earlier modules.
# Sets globals: AI_BUDGET_GB AI_TIER
# =============================================================================

# Model catalog: name|params|approx Q4 size(GB). One per line.
# (Sizes are approximate Ollama Q4_K_M download sizes.)
_ai_catalog() {
  cat <<'EOF'
llama3.2:1b|1B|1.3
qwen2.5:3b|3B|1.9
llama3.2:3b|3B|2.0
phi3.5|3.8B|2.2
mistral:7b|7B|4.1
llama3.1:8b|8B|4.7
qwen2.5:7b|7B|4.7
qwen2.5-coder:7b|7B|4.7
gemma2:9b|9B|5.4
phi4:14b|14B|9.1
qwen2.5:14b|14B|9.0
qwen2.5-coder:14b|14B|9.0
gemma2:27b|27B|16.0
qwen2.5:32b|32B|20.0
llama3.3:70b|70B|43.0
EOF
}

# Decide the memory budget available to a model (GB) and a tier label.
_ai_compute_budget() {
  local total vram
  total="${MEM_TOTAL_GB:-0}"
  vram="${GPU_VRAM_GB:-0}"

  if awk -v v="$vram" 'BEGIN{exit !(v>0.5)}'; then
    # Discrete GPU: VRAM is the practical limiter for fast inference.
    AI_BUDGET_GB=$(awk -v v="$vram" 'BEGIN{printf "%.1f", v*0.92}')
    AI_BACKEND="discrete GPU VRAM (${vram} GB)"
  elif [ "${IS_UNIFIED:-0}" = "1" ]; then
    # Apple Silicon unified memory: leave headroom for macOS + a couple apps.
    AI_BUDGET_GB=$(awk -v t="$total" 'BEGIN{b=t-4.5; if(b<1)b=1; printf "%.1f", b}')
    AI_BACKEND="unified memory (Metal GPU shares ${total} GB)"
  else
    # CPU-only path.
    AI_BUDGET_GB=$(awk -v t="$total" 'BEGIN{b=t-3; if(b<1)b=1; printf "%.1f", b}')
    AI_BACKEND="CPU only (no GPU acceleration detected — expect slow generation)"
  fi

  # Tier from budget. Thresholds use the same "size*1.3 comfortable-fit" rule as
  # the model table below, so the tier label and the per-model verdicts agree.
  if   awk -v b="$AI_BUDGET_GB" 'BEGIN{exit !(b>=55.9)}'; then AI_TIER_KEY="workstation"; AI_TIER="Workstation — 70B class"
  elif awk -v b="$AI_BUDGET_GB" 'BEGIN{exit !(b>=26.0)}'; then AI_TIER_KEY="high";        AI_TIER="High — up to ~32B Q4"
  elif awk -v b="$AI_BUDGET_GB" 'BEGIN{exit !(b>=20.8)}'; then AI_TIER_KEY="strong";      AI_TIER="Strong — up to ~27B Q4"
  elif awk -v b="$AI_BUDGET_GB" 'BEGIN{exit !(b>=11.7)}'; then AI_TIER_KEY="capable";     AI_TIER="Capable — up to ~14B Q4"
  elif awk -v b="$AI_BUDGET_GB" 'BEGIN{exit !(b>=6.0)}';  then AI_TIER_KEY="comfortable"; AI_TIER="Comfortable — 7–9B daily (14B tight)"
  elif awk -v b="$AI_BUDGET_GB" 'BEGIN{exit !(b>=3.0)}';  then AI_TIER_KEY="entry";       AI_TIER="Entry — up to ~7B (tight)"
  else AI_TIER_KEY="minimal"; AI_TIER="Minimal — 1–3B models"
  fi
}

# fit verdict for a model size vs budget: yes / tight / no
_ai_fit() {
  awk -v s="$1" -v b="$2" 'BEGIN{
    if (s*1.3 <= b)      print "yes";
    else if (s <= b)     print "tight";
    else                 print "no";
  }'
}

mod_ai() {
  section "Local AI / LLM Capability"
  _ai_compute_budget

  field "Inference backend" "$AI_BACKEND"
  field "Usable memory budget" "~${AI_BUDGET_GB} GB for the model + context"
  field "Capability tier" "$AI_TIER"

  case "$AI_BACKEND" in
    CPU*) status warn "No GPU acceleration detected. Models will run on CPU — usable for small models, but slow. A GPU or Apple Silicon is strongly recommended." ;;
    *)    status ok   "Hardware-accelerated local inference is available." ;;
  esac

  # ---- Model fit table -----------------------------------------------------
  subsection "Which models fit (Ollama, Q4 quantization)"
  printf '  %s%-22s %-7s %-9s %-7s%s\n' "$BOLD" "MODEL" "PARAMS" "~SIZE" "FITS?" "$RST"
  table_begin "Model" "Params" "~Size (Q4)" "Fits this machine?"

  _ai_catalog | while IFS='|' read -r name params size; do
    [ -n "$name" ] || continue
    verdict=$(_ai_fit "$size" "$AI_BUDGET_GB")
    case "$verdict" in
      yes)   mark="✅ yes";    col="$GRN" ;;
      tight) mark="🟡 tight";  col="$YLW" ;;
      no)    mark="🔴 too big"; col="$RED" ;;
    esac
    printf '  %-22s %-7s %-9s %s%s%s\n' "$name" "$params" "${size}GB" "$col" "$mark" "$RST"
    table_row "\`$name\`" "$params" "${size} GB" "$mark"
  done

  # ---- Recommended starter set (based on tier) -----------------------------
  subsection "Recommended starter set"
  case "$AI_TIER_KEY" in
    minimal)
      bullet "General: \`llama3.2:1b\` (1.3 GB) or \`qwen2.5:3b\` (1.9 GB)"
      bullet "Keep contexts short; expect small-model quality."
      ;;
    entry)
      bullet "General: \`llama3.1:8b\` (4.7 GB) — may be tight; fall back to \`llama3.2:3b\`"
      bullet "Coding:  \`qwen2.5-coder:7b\` (4.7 GB)"
      bullet "Embeddings (RAG/search): \`nomic-embed-text\` (0.3 GB)"
      ;;
    comfortable)
      bullet "General: \`llama3.1:8b\` (4.7 GB) — fast daily driver"
      bullet "Coding:  \`qwen2.5-coder:7b\` (4.7 GB) — pairs with the VS Code 'continue.dev' extension"
      bullet "Embeddings: \`nomic-embed-text\` (0.3 GB)"
      bullet "Step up for hard problems: \`qwen2.5:14b\` / \`phi4:14b\` (close other apps first)"
      ;;
    capable)
      bullet "General: \`qwen2.5:14b\` (9 GB) or \`phi4:14b\` (9 GB)"
      bullet "Coding:  \`qwen2.5-coder:14b\` (9 GB)"
      bullet "Fast daily option: \`llama3.1:8b\` (4.7 GB)"
      bullet "Embeddings: \`nomic-embed-text\` (0.3 GB)"
      ;;
    strong)
      bullet "General: \`gemma2:27b\` (16 GB); use \`qwen2.5:14b\` (9 GB) for speed"
      bullet "Coding:  \`qwen2.5-coder:14b\` (9 GB)"
      bullet "Embeddings: \`mxbai-embed-large\` (0.7 GB)"
      ;;
    high)
      bullet "General: \`qwen2.5:32b\` (20 GB)"
      bullet "Coding:  \`qwen2.5-coder:32b\` (20 GB)"
      bullet "Embeddings: \`mxbai-embed-large\` (0.7 GB)"
      ;;
    workstation)
      bullet "General: \`llama3.3:70b\` (43 GB) for top local quality"
      bullet "Coding:  \`qwen2.5-coder:32b\` for faster turnaround"
      bullet "You can keep multiple models loaded at once."
      ;;
  esac

  subsection "Install & first run"
  bullet "Install: \`brew install ollama\` then \`brew services start ollama\`  (or download from ollama.com)"
  bullet "Pull + chat: \`ollama run llama3.1:8b\`"
  bullet "List / remove: \`ollama list\` · \`ollama rm <model>\`  (each model is multiple GB — mind disk)"

  # Speed expectation (qualitative + arch-aware)
  subsection "Speed expectation"
  case "$AI_BACKEND" in
    CPU*)            note "CPU-only: small models a few tokens/sec; 7B may be ~1–4 tok/s. Fine for tinkering, not interactive." ;;
    *VRAM*)          note "On a discrete GPU, 7–8B models are very fast (often 40–100+ tok/s); larger models scale with VRAM + bandwidth." ;;
    *unified*)       note "On Apple Silicon, 7–8B≈10–25 tok/s, 14B≈6–12 tok/s (varies by chip tier). Generation speed is memory-bandwidth-bound." ;;
  esac

  if [ "$AI_TIER_KEY" = "comfortable" ] && [ "${IS_UNIFIED:-0}" = "1" ]; then
    note "Tip: to fit a 14B model, close other apps. On Apple Silicon you can also raise the GPU memory limit temporarily: \`sudo sysctl iogpu.wired_limit_mb=12288\` (reverts on reboot — don't starve macOS)."
  fi

  j ai_budget_gb "${AI_BUDGET_GB:-}"
  j ai_tier "${AI_TIER:-}"
}

# ----------------------------- mod_recommend.sh -----------------------------
# =============================================================================
# SysScope — mod_recommend.sh : health scorecard + workload guidance
# Reads globals set by earlier modules.
# =============================================================================

mod_recommend() {
  section "Health Scorecard & Recommendations"

  subsection "Health scorecard"
  printf '  %s%-16s %-8s %s%s\n' "$BOLD" "AREA" "RATING" "NOTE" "$RST"
  table_begin "Area" "Rating" "Note"

  # --- Disk ---
  local d_rate d_note
  if   [ "${DISK_USED_PCT:-0}" -ge 90 ] 2>/dev/null; then d_rate="🟥 critical"; d_note="Only ${DISK_FREE_GB} GB free — reclaim space before installing tools/models."
  elif [ "${DISK_USED_PCT:-0}" -ge 75 ] 2>/dev/null; then d_rate="🟡 tight";    d_note="${DISK_FREE_GB} GB free — plan cleanup."
  else d_rate="🟢 good"; d_note="${DISK_FREE_GB} GB free."
  fi
  printf '  %-16s %-8s %s\n' "Disk" "$d_rate" "$d_note"; table_row "Disk" "$d_rate" "$d_note"

  # --- Memory ---
  local m_rate m_note
  if   [ "${MEM_TOTAL_GB:-0}" -ge 32 ] 2>/dev/null; then m_rate="🟢 great"; m_note="${MEM_TOTAL_GB} GB — multitask heavy workloads."
  elif [ "${MEM_TOTAL_GB:-0}" -ge 16 ] 2>/dev/null; then m_rate="🟢 good";  m_note="${MEM_TOTAL_GB} GB — one very-heavy workload at a time."
  elif [ "${MEM_TOTAL_GB:-0}" -ge 8  ] 2>/dev/null; then m_rate="🟡 limited"; m_note="${MEM_TOTAL_GB} GB — light dev + small models."
  else m_rate="🟥 low"; m_note="${MEM_TOTAL_GB} GB — small tasks only."
  fi
  printf '  %-16s %-8s %s\n' "Memory" "$m_rate" "$m_note"; table_row "Memory" "$m_rate" "$m_note"

  # --- Local AI ---
  local a_note="${AI_TIER:-unknown} (~${AI_BUDGET_GB:-?} GB budget)"
  printf '  %-16s %-8s %s\n' "Local AI" "🔭" "$a_note"; table_row "Local AI" "ℹ️" "$a_note"

  # --- Battery (if laptop) ---
  if [ -n "${PWR_PCT:-}" ]; then
    local b_rate="🟢 ok"
    [ "${PWR_ONBATT:-0}" = "1" ] && [ "${PWR_PCT:-100}" -le 20 ] 2>/dev/null && b_rate="🟡 low"
    printf '  %-16s %-8s %s\n' "Battery" "$b_rate" "${PWR_PCT}% (${PWR_SRC:-?})"
    table_row "Battery" "$b_rate" "${PWR_PCT}% (${PWR_SRC:-?})"
  fi

  # --- Concurrency guidance keyed off RAM ---
  subsection "What you can run — and how to combine it"
  if [ "${MEM_TOTAL_GB:-0}" -ge 32 ] 2>/dev/null; then
    bullet "You can comfortably run a local model + a container stack + an editor together."
    bullet "A VM or emulator alongside a 7–8B model is fine."
  elif [ "${MEM_TOTAL_GB:-0}" -ge 16 ] 2>/dev/null; then
    bullet "Golden rule: run ONE very-heavy workload at a time (big model OR VM OR mobile emulator), surrounded by light tools."
    bullet "🟢 Fine together: editor + dev server + 1 browser + a 7–8B model (≈12 GB)."
    bullet "🟢 Fine together: editor + 1 mobile emulator + 1 browser."
    bullet "🔴 Avoid: VM (≈8 GB) + 7B model; or Android + iOS emulators + a model at once."
    bullet "Cap Docker/OrbStack RAM to 3–4 GB; suspend VMs when idle; prefer real devices over emulators."
  elif [ "${MEM_TOTAL_GB:-0}" -ge 8 ] 2>/dev/null; then
    bullet "Stick to one heavy thing: a 3–7B model OR a light VM OR one emulator — not combinations."
    bullet "Keep browser tabs minimal; close apps before launching a model."
  else
    bullet "Run a single lightweight task at a time; 1–3B models only; avoid VMs/emulators."
  fi

  # --- Arch-specific virtualization note ---
  case "$SYS_ARCH" in
    arm64|aarch64) bullet "Virtualization is ARM-only here: run Windows 11 ARM / ARM Linux guests (x86 ISOs won't boot).";;
  esac

  # --- Top actions, prioritized ---
  subsection "Top next actions"
  local n=1
  if [ "${DISK_USED_PCT:-0}" -ge 85 ] 2>/dev/null; then
    bullet "$n. 🟥 Free disk space first (Downloads, caches, old VM snapshots, build dirs)."; n=$((n+1))
  fi
  if ! have brew && [ "$SYS_OS" = "macos" ]; then
    bullet "$n. Install Homebrew (package manager) — most tools below install through it."; n=$((n+1))
  fi
  if ! have ollama; then
    bullet "$n. Install Ollama and pull a starter model (see Local AI section above)."; n=$((n+1))
  fi
  if ! have docker && ! have orb; then
    bullet "$n. For containers, install OrbStack (lighter than Docker Desktop on laptops) and cap its RAM."; n=$((n+1))
  fi
  if have node && ! have pnpm; then
    bullet "$n. Many JS projects? Enable pnpm (\`corepack enable\`) — one shared package store saves lots of disk."; n=$((n+1))
  fi
  bullet "$n. Keep the machine on AC power for heavy or sustained sessions."
}

# ----------------------------- audit.sh (orchestrator) -----------------------------
# =============================================================================
#  🔭 SysScope — System Capability & AI-Readiness Audit
#  Portable, modular, read-only auditor for macOS (Linux best-effort).
#  Repo: https://github.com/aoneahsan/sysscope   ·   License: MIT
#  Run without install:  npx sysscope   (or latest from source: npx github:aoneahsan/sysscope)
#
#  Usage:   ./audit.sh [options]
#  Quick:   ./audit.sh --quick
#  Share:   ./audit.sh --share          (redacts serials/hostname)
#  Help:    ./audit.sh --help
# =============================================================================

SYSSCOPE_VERSION="1.0.3"

# ---- Locate & load modules (this block is stripped in the bundled build) ----
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" 2>/dev/null && pwd)

# ---- Defaults ---------------------------------------------------------------
PRESET=""                 # full|quick|ai  ("" => ask if interactive, else full)
USE_COLOR=1
REDACT=0
DEEP=0
EMIT_JSON=0
JSON_FILE=""
WANT_REPORT=1
FORCE_NONINTERACTIVE=0
REPORT_FILE=""
SYSSCOPE_GIST_URL="https://github.com/aoneahsan/sysscope"

usage() {
  cat <<EOF
🔭 SysScope v$SYSSCOPE_VERSION — System Capability & AI-Readiness Audit

USAGE:
  ./audit.sh [options]

PRESETS:
  -f, --full         Full audit (default): hardware + software + AI + advice
  -q, --quick        Faster: skips software inventory & deep disk scan
  -a, --ai-only      Just the local-AI / LLM capability assessment

OUTPUT:
  -o, --output FILE  Write the markdown report to FILE
                     (default: ./sysscope-report-YYYYMMDD-HHMMSS.md)
      --no-report    Terminal only; don't write a file
      --json [FILE]  Also emit machine-readable JSON of key metrics
      --deep         Include slow probes (largest items in home folder)

PRIVACY:
      --share        Redact serial numbers, UUIDs and hostname (safe to post)
      --redact       Alias for --share

BEHAVIOR:
  -y, --yes          Non-interactive: accept defaults, ask nothing
      --no-color     Disable ANSI colors
      --gist-url URL Set the feedback URL printed in the report
  -V, --version      Print version and exit
  -h, --help         Show this help and exit

EXAMPLES:
  ./audit.sh                       # interactive, full audit, saves a report
  ./audit.sh --quick --yes         # fast, unattended
  ./audit.sh --ai-only             # "what models can I run?"
  ./audit.sh --share -o report.md  # redacted, shareable report
  ./audit.sh --json metrics.json   # full audit + JSON metrics

SysScope is read-only: it inspects, it never changes your system.
EOF
}

parse_args() {
  while [ $# -gt 0 ]; do
    case "$1" in
      -f|--full)    PRESET="full" ;;
      -q|--quick)   PRESET="quick" ;;
      -a|--ai-only) PRESET="ai" ;;
      -o|--output)  shift; REPORT_FILE="$1" ;;
      --no-report)  WANT_REPORT=0 ;;
      --json)
        EMIT_JSON=1
        case "$2" in -*|"") : ;; *) JSON_FILE="$2"; shift ;; esac
        ;;
      --deep)       DEEP=1 ;;
      --share|--redact) REDACT=1 ;;
      -y|--yes|--non-interactive) FORCE_NONINTERACTIVE=1 ;;
      --no-color)   USE_COLOR=0 ;;
      --gist-url)   shift; SYSSCOPE_GIST_URL="$1" ;;
      -V|--version) printf 'SysScope %s\n' "$SYSSCOPE_VERSION"; exit 0 ;;
      -h|--help)    usage; exit 0 ;;
      *) printf 'Unknown option: %s (try --help)\n' "$1" >&2; exit 2 ;;
    esac
    shift
  done
}

banner() {
  [ "$USE_COLOR" = "1" ] && [ -t 1 ] || { printf 'SysScope v%s — system capability & AI-readiness audit\n' "$SYSSCOPE_VERSION"; return; }
  printf '%s%s' "$BOLD" "$CYN"
  printf '  ┌─────────────────────────────────────────────┐\n'
  printf '  │   🔭  S Y S S C O P E   v%-7s            │\n' "$SYSSCOPE_VERSION"
  printf '  │   System Capability & AI-Readiness Audit    │\n'
  printf '  └─────────────────────────────────────────────┘%s\n' "$RST"
}

modules_for_preset() {
  case "$1" in
    ai)    printf 'mod_system mod_cpu mod_memory mod_gpu mod_ai mod_recommend' ;;
    quick) printf 'mod_system mod_cpu mod_memory mod_gpu mod_storage mod_power mod_ai mod_recommend' ;;
    *)     printf 'mod_system mod_cpu mod_memory mod_gpu mod_storage mod_power mod_software mod_ai mod_recommend' ;;
  esac
}

main() {
  parse_args "$@"

  # Interactivity: only when both ends are a TTY and not forced off.
  if [ "$FORCE_NONINTERACTIVE" != "1" ] && [ -t 0 ] && [ -t 1 ]; then INTERACTIVE=1; else INTERACTIVE=0; fi

  setup_colors
  banner

  # Interactive choices (only when nothing explicit was requested)
  if [ "$INTERACTIVE" = "1" ] && [ -z "$PRESET" ]; then
    sel=$(ask_menu "What would you like to run?" \
      "Full audit (recommended)" \
      "Quick audit (faster)" \
      "AI-only — what models can I run?")
    case "$sel" in 1) PRESET="full";; 2) PRESET="quick";; 3) PRESET="ai";; esac
  fi
  [ -z "$PRESET" ] && PRESET="full"

  # Report path
  if [ "$WANT_REPORT" = "1" ]; then
    if [ -z "$REPORT_FILE" ]; then
      default_report="./sysscope-report-$(date +%Y%m%d-%H%M%S).md"
      REPORT_FILE=$(ask_str "Save report to" "$default_report")
    fi
  else
    REPORT_FILE=""
  fi

  # Redaction prompt (interactive only, if not already set)
  if [ "$INTERACTIVE" = "1" ] && [ "$REDACT" = "0" ]; then
    if ask_yn "Redact serials/hostname so the report is safe to share publicly" "n"; then REDACT=1; fi
  fi

  # JSON default path
  if [ "$EMIT_JSON" = "1" ] && [ -z "$JSON_FILE" ]; then
    if [ -n "$REPORT_FILE" ]; then JSON_FILE="${REPORT_FILE%.md}.json"; else JSON_FILE="./sysscope-metrics.json"; fi
  fi

  # Go
  report_init
  json_init
  run_list=$(modules_for_preset "$PRESET")
  for fn in $run_list; do
    "$fn"
  done
  report_finalize
  json_finalize

  # Summary
  printf '\n'; hr
  if [ -n "$REPORT_FILE" ] && [ -f "$REPORT_FILE" ]; then
    printf '%s✓%s Markdown report saved: %s%s%s\n' "$GRN" "$RST" "$BOLD" "$REPORT_FILE" "$RST"
  fi
  if [ "$EMIT_JSON" = "1" ] && [ -n "$JSON_FILE" ] && [ -f "$JSON_FILE" ]; then
    printf '%s✓%s JSON metrics saved:    %s%s%s\n' "$GRN" "$RST" "$BOLD" "$JSON_FILE" "$RST"
  fi
  printf '%sFeedback / improvements:%s %s\n' "$DIM" "$RST" "$SYSSCOPE_GIST_URL"

  # Offer to open the report
  if [ "$INTERACTIVE" = "1" ] && [ -n "$REPORT_FILE" ] && [ -f "$REPORT_FILE" ]; then
    if [ "$SYS_OS" = "macos" ] && have open; then
      ask_yn "Open the report now" "n" && open "$REPORT_FILE"
    elif [ "$SYS_OS" = "linux" ] && have xdg-open; then
      ask_yn "Open the report now" "n" && xdg-open "$REPORT_FILE" >/dev/null 2>&1
    fi
  fi
}

main "$@"
