#!/usr/bin/env bash
# =============================================================================
# SysScope — build.sh
# Concatenates the modular files into a single distributable: audit-bundle.sh
# Use the bundle for curl|bash installs or when you want to ship ONE file.
# Edit the modular *.sh files (not the bundle), then re-run this.
# =============================================================================
set -e
cd "$(dirname "$0")"

OUT="audit-bundle.sh"
MODS="lib_core lib_report mod_system mod_cpu mod_memory mod_gpu mod_storage mod_power mod_software mod_ai mod_recommend"

# Verify all parts exist
for m in $MODS audit; do
  [ -f "$m.sh" ] || { printf 'build.sh: missing %s.sh\n' "$m" >&2; exit 1; }
done

{
  printf '#!/usr/bin/env bash\n'
  printf '# =============================================================================\n'
  printf '# SysScope (bundled single-file build) — auto-generated by build.sh\n'
  printf '# Do NOT edit this file directly; edit the modular sysscope/*.sh sources,\n'
  printf '# then re-run ./build.sh. License: MIT.\n'
  printf '# =============================================================================\n\n'

  for m in $MODS; do
    printf '# ----------------------------- %s.sh -----------------------------\n' "$m"
    sed '1{/^#!/d;}' "$m.sh"
    printf '\n'
  done

  printf '# ----------------------------- audit.sh (orchestrator) -----------------------------\n'
  # Strip the shebang and the module-sourcing block (already inlined above).
  sed '1{/^#!/d;}' audit.sh | awk '
    /# >>> SYSSCOPE_SOURCE_START/ { skip=1; next }
    /# >>> SYSSCOPE_SOURCE_END/   { skip=0; next }
    skip { next }
    { print }
  '
} > "$OUT"

chmod +x "$OUT"
printf 'Built %s (%s lines).\n' "$OUT" "$(wc -l < "$OUT" | tr -d ' ')"
printf 'Try it:  ./%s --help\n' "$OUT"
printf 'Ship it: upload %s to a gist, or:  curl -fsSL <raw-url> | bash\n' "$OUT"
